version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm test

  push_to_dh:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run: npm run ci:docker

workflows:
  version: 2
  build_test_push_to_dh:
    jobs:
      - build

      # - test:
      #     requires:
      #       - build

      # - push_to_dh:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         # Push to docker hub only if it is master
      #         only: master
